### PR TITLE
Feature/1050 modify cascade type question to support entities

### PR DESCRIPTION
**Pull request by ifirmawan**
### BACKEND

- [x] Update form details API to add parentCascade
- [x] Example entities seeder related to the form JSON

### MOBILE

- [x] Implements cascade entities
- [x] Update TypeCascade test

### CODE REVIEW

**Review by dedenbangkit — CHANGES_REQUESTED** [review]
Hi @ifirmawan, this isn't work without Entity seeder. Could you please create seeder for the example entities you have in HH Form?

**Comment by ifirmawan** [comment]
> Hi @ifirmawan, this isn't work without Entity seeder. Could you please create seeder for the example entities you have in HH Form?

Sure mas @dedenbangkit , on it

**Review by dedenbangkit — APPROVED** [review]

**Review by dedenbangkit — CHANGES_REQUESTED** [review]
Hide question if previous administration answer is null

**Comment by ifirmawan** [comment]
> > > Hide question if previous administration answer is null
> > 
> > 
> > Hi mas @dedenbangkit , I've fixed it and it's ready for review. Thank you
> 
> Hi @ifirmawan, please fix the conflict first

Noted, done mas.

**Pull request merged**
